server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: kash-save-backend

  profiles:
    active: dev

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:kash_save_db}
    username: ${DB_USERNAME:kash_user}
    password: ${DB_PASSWORD:kash_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
      enabled: true

  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY:mySecretKey}
      expiration: ${JWT_EXPIRATION:86400000}

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=300s

  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    com.kashsave: DEBUG
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:4200}
  file-upload:
    max-size: ${MAX_FILE_SIZE:10MB}
  upload:
    dir: ${UPLOAD_DIR:uploads}
    max-file-size: ${MAX_UPLOAD_FILE_SIZE:5MB}
  base-url: ${BASE_URL:http://localhost:8080}
  payment:
    stripe:
      public-key: ${STRIPE_PUBLIC_KEY:}
      secret-key: ${STRIPE_SECRET_KEY:}
  security:
    client-token: ${CLIENT_TOKEN:Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9}