global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'ev-booking-backend'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres:9187']
    scrape_interval: 30s

  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis:9121']
    scrape_interval: 30s

  - job_name: 'nginx-exporter'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s